### ISSUE TITLE
Show the Counter Programmatically

### ISSUE THREAD

**Issue by drosanda** [dfactoryplugins/post-views-counter#10]
Can I show the counter programmatically, such as get_the_author(); ?

**Comment by Swennet** [comment]
`<?php echo do_shortcode('[post-views]'); ?>`

**Comment by Tigzy** [comment]
Hello, is it possible to get the count undecorated? (raw integer)

**Comment by bartoszarendt** [comment]
Yep. pvc_get_post_views function.

**Comment by drosanda** [comment]
okay thanks
