### ISSUE TITLE
1.2.9 Changelog?

### ISSUE THREAD

**Issue by majestica** [dfactoryplugins/post-views-counter#15]
Hi, at https://wordpress.org/plugins/post-views-counter/ I see the new version 1.2.9, please tell me what changes are made? hmm on git old version 1.2.8, last stable 1.2.9?

**Comment by Beee4life** [comment]
It seems Git is not kept up to date but the changelog can always be found on the developers tab of the plugin: @ https://wordpress.org/plugins/post-views-counter/#developers
