### ISSUE TITLE
More strict option to set counts interval

### ISSUE THREAD

**Issue by NasirNobin** [dfactoryplugins/post-views-counter#16]
Currently **option to set counts interval** uses the cookie to manage counts interval. This is good for most of the sites, I guess. But I'm working on a site where we need to be very strict about this. 

Now user can just open an incognito browser window and hit that URL. And they can bypass the **counts interval** thing easily. 

Maybe we can add a new table where we can log user details (user_id, IP, user agent, browser etc) and before **counting visit** just check if that user's hit is already counted in the interval.

Also, to keep the log table small, we can set a wp cron to clear up old entries.

**Comment by bartoszarendt** [comment]
It's already available as an additional feature since v1.2.11 (not yet uploaded to git)

**Comment by NasirNobin** [comment]
Thank you! @bartoszarendt
