### ISSUE TITLE
Your cron takes over other cron jobs

### ISSUE THREAD

**Issue by Beee4life** [dfactoryplugins/post-views-counter#17]
I tried to add this issue to your support forum but it failed twice, so doing it here.

Your plugin adds a cron schedule which already exists in Wordpress default, namely the daily schedule, as explained [here](https://codex.wordpress.org/Plugin_API/Filter_Reference/cron_schedules).

By registering this, it overtakes the default "daily" schedule so now the name of your cron schedule appears on places where it's not expected (or wanted). This can be see [this screenshot](https://imgur.com/a/tBLE1).

Adrotate is now linked to your cron as is the custom plugin with sd prefix. And there are more (outside of screenshot).

It is my opinion you don't need to add this daily schedule because it already exists. I have found 4 possible solutions to avoid this. 3 are on the plugin side and 1 is on the user side.

1. Remove your cron schedule and add use daily for the cron job that uses it (there is only 1).
2. Place the adding of the cron_schedule in an IF statement. Something like this (this code doesn't work, but gives an idea of what I mean):
    ```
    if ( ! array_key_exists( 'daily', wp_cron_schedules() ) ) {
        // add your schedule
    }
    ```
3. Change the interval of your cron schedule to 86401 (1 second higher). This will stop the intereference with the default schedule.
4. Add a filter which unregisters your cron schedule and registers a new one with the same name but with a 86401 interval, see code below (tested and works).
    ```
    public function change_cron_time_intervals( $schedules ) {

        unset( $schedules['post_views_counter_interval'] );
        $schedules['post_views_counter_interval'] = array(
            'interval'   => 86401,
            'display'    => __( 'Post Views Counter reset daily counts interval', 'post-views-counter' )
        );

        return $schedules;
    }
    ```

**Comment by bartoszarendt** [comment]
There is no problem like that and no cron jobs get's overwritten. 

We've double checked everything end what you say is based on WP Crontrol plugin. Turns out it's a bug in that plugin that displays the last cron job of a given interval (like daily) and not the all cron jobs of it. This way you don't see all the jobs, just the recently added.

**Comment by Beee4life** [comment]
Sorry but I disagree :) I'm not saying what you say is incorrect, but it doesn't seem likely to me. Without your plugin it all works as expected. When I activate your plugin it goes haywire...

Can you please elaborate a bit more why you think it's a bug in the crontrol plugin ?

**Comment by bartoszarendt** [comment]
Schedules are not unique by interval name (like daily) but cron job id. The crontrol plugin does not distinguish that i think and it only displays one job per interval. What you see here https://codex.wordpress.org/Plugin_API/Filter_Reference/cron_schedules mean you can add multiple jobs to existings sets and that what PVC is doing.

**Comment by Beee4life** [comment]
Yes but your schedule appears to be overriding the names that were assigned by Wordpress.

Which results in my custom plugins, which have a cron job, using a cron with your (plugin name) on it, which I don't see as correct. 

I don't want a cron to do something custom for me, to be assigned to a cron job from your plugin.

**Comment by bartoszarendt** [comment]
It's not overriding anything. It's adding a new interval name of the exact same value as WP native daily schedule. There's no conflict. The thing is WP Crontrol takes only one name schedule of a given interval (daily).

Moreover, if there was an issue like that PVC would disable lot's of WP native functionality based on cron. We don't see this happening nor we have been reported an issue like that from anyone.

**Comment by Beee4life** [comment]
I have never said it disables anything... All I said was your plugin replaces Wordpress' cron name..

Now all my custom plugins show your cron schedule instead of Wordpress'. I don't want that because it's not 'expected' Wordpress behaviour.

You didn't even need to register your own cron schedule. You can just use WP's daily cron because it's exactly the same, apart from the name. That way your name wouldn't show on unwanted places in Crontrol.

Why can every other plugin make it work, but you can't ???

**Comment by Beee4life** [comment]
I'm wondering if you will ever see the issue at hand and fix it.... Have looked into various plugins and every single one of them, is doing the opposite of what you're doing...

**Comment by Beee4life** [comment]
@bartoszarendt

**Comment by Beee4life** [comment]
Too bad your plugin does this... and no follow-up. Will look for another one which follows WP conventions better.
