### ISSUE TITLE
high load problem

### ISSUE THREAD

**Issue by majestica** [dfactoryplugins/post-views-counter#19]
Hi, you have a very cool plugin, but I have a buggy site for high traffic (4000 people per minute for example), I use counting in RAM, and I add information about views on the crown every 3 minutes, I think the problem is related to the fact, that counting views is through admin-ajax.php, because connecting this script draws a lot of dependencies of WordPress, can you add your own script for counting in order not to drag all the dependencies of WordPress, then this process would be easier? can you advise something? Thanks

**Comment by bartoszarendt** [comment]
We have a plan to introduce sth like "Fast ajax" method that will not rely on admin-ajax.php but a custom callback and SHORTINIT loading minimum WordPress environment. This would make things faster but on the other hand could break if someone is hooking into the plugin to do some custom things when the views couning processes. We'll see.

According to your situation I'd switch to PHP mode instead - it would not produce additional requests (but on the other hand will not be precise if you're using full page caching).

**Comment by majestica** [comment]
I use Batcache for FULL page caching....

And how soon do you have it in your plans? the same can be done optionally in the plugin, use admin-ajax.php or your super fast count =) Thanks for your reply

**Comment by bartoszarendt** [comment]
Please search us via contact for here https://dfactory.eu/contact/ and point to this conversation - we'll have a surprise for you.
