### ISSUE TITLE
PHP Function for pageviews?

### ISSUE THREAD

**Issue by erikmolenaarnl** [dfactoryplugins/post-views-counter#22]
Hi,

Awesome code! Thanks!

I was wondering, do you have a PHP function available to retrieve the pageviews for a specific post ID in PHP? So I can integrate your plugin with other plugins?

And if yes, how can I best test your plugin is active?

Looking forward to your reply. Thanks!

**Comment by bartoszarendt** [comment]
Sure there is - pvc_get_post_views( $post_id ).
All the available public functions are located in functions.php file
