### ISSUE TITLE
Counter doesn't check cookie before count (FastAJAX mode)

### ISSUE THREAD

**Issue by CryMasK** [dfactoryplugins/post-views-counter#23]
Hello,
I use FastAJAX  mode for counting views, and set count interval to 24 hours.
I found a strange problem, everytime I refresh the page, the post views will count once.

In `includes/counter.php`
`check_cookie()` will be triggered by `plugins_loaded` actoin and `check_post($id)` will run after it receive a AJAX request

I did a small test (give each `Post_Views_Counter_Counter` a random id),
it seem like these two function run on different class instances, so when `check_post($id)` run, it always can't access cookie data.

I'm not sure if it is the key to cause this problem, now I simply fix this problem by adding one line `$this->check_cookie();` to `check_post($id)`, force it initialize cookie first.

**Comment by bartoszarendt** [comment]
Maybe the problem is that the check_cookie doesn't trigger in Fast Ajax mode because it's initialized in SHORTINIT because the plugins_loaded action does not fire there.

So I would try that instead of forcing check_cookie() everywhere:

```
if ( defined( 'SHORTINIT' ) && SHORTINIT ) {
	$this->check_cookie();
}
```
