### ISSUE TITLE
Get the post views count programmatically 

### ISSUE THREAD

**Issue by piotrkulpinski** [dfactoryplugins/post-views-counter#6]
Hi there,
I just wanted to ask if there's a way to get the views count of a post in from the WP_Post object?

Thanks

**Comment by bartoszarendt** [comment]
We're working on it at this very moment - we'll be available in the next update.
I'm talking about post_views in post object returned in wp_query and get_posts(). The get_post() function however (used to get single post object) does not provide any way/filter to modify the output.

**Comment by piotrkulpinski** [comment]
That's what I'm looking for exactly, thanks!
Do you have any date when this could be available?

**Comment by bartoszarendt** [comment]
Today / tomorrow i think.

**Comment by piotrkulpinski** [comment]
Any luck with releasing this update?
Thanks

**Comment by bartoszarendt** [comment]
It's been released in 1.1.2 It's automatically available if you use 'orderby' => 'post_views' parameter. But you can force it to any query with pvc_extend_post_object filter hook located in includes/query.php

**Comment by piotrkulpinski** [comment]
Thanks!
